package aksstoredemo:rules@0.1.1;

interface types {
    record product {
        id: s32,
        name: string,
        price: float32,
        description: string,
        image: string,
    }

    variant error {
        engine-internal-error(string),
        invalid-product(string),
        naming-standards-violation(string),
        pricing-standards-violation(string)
    }
}

interface engine {
    use types.{product, error};

    execute: func(input: product) -> result<product, error>;
}

interface logging {
    resource logger {
        log: func(msg: string);
    }

    get-logger: func() -> logger;
}

world service-host {
    import logging;
    export engine;
}

world rule {
    import logging;
    export engine;
}

world rule-extension {
    import logging;
    import engine;
    export engine;
}
