### 
POST /
Host: localhost:3000
Content-Type: application/json

{
    "customerId": "1234567890",
    "items": [
        {
            "name": "Potato Chips",
            "quantity": 1,
            "price": 10
        },
        {
            "name": "Chocolate Chip Cookies",
            "quantity": 2,
            "price": 20
        }
    ]
}