####################################
### ORDER SERVICE
####################################

### Get order service health
GET  /health
Host: localhost:3000

### Send order to order service
POST /
Host: localhost:3000
Content-Type: application/json

{
    "customerId": "1234567890",
    "items": [
        {
            "productId": 1,
            "quantity": 1,
            "price": 10
        },
        {
            "productId": 2,
            "quantity": 2,
            "price": 20
        }
    ]
}

####################################
### MAKELINE SERVICE
####################################

### Get makeline service health
GET /health
Host: localhost:3001

### Fetch orders from rabbitmq and put into mongodb
GET /order/fetch
Host: localhost:3001

### Get order for processing
GET /order/44821
Host: localhost:3001

### Update the order
PUT /order
Host: localhost:3001
Content-Type: application/json

{
    "orderId": "65982",
    "customerId": "1022466235",
    "items": [
        {
            "productId": 0,
            "quantity": 2,
            "price": 22.428429
        },
        {
            "productId": 0,
            "quantity": 1,
            "price": 99.63117
        },
        {
            "productId": 0,
            "quantity": 2,
            "price": 93.84932
        }
    ],
    "status": 1
}

####################################
### AI SERVICE
####################################

### Get ai service health
GET /health
Host: localhost:5001

### Generate product description
POST /generate/description 
Host: localhost:5001
Content-Type: application/json

{
    "name": "Seafarer's Tug Rope",
    "tags": ["toy","dog"]
}

####################################
### PRODUCT SERVICE
####################################

### Get product service health
GET /health
Host: localhost:3002

### Get product service health
HEAD /health
Host: localhost:3002

### Get products
GET /
Host: localhost:3002

### Add product
POST /
Host: localhost:3002
Content-Type: application/json

{
    "id": 0,
    "name": "Where My Dogs At Collar Tag",
    "price": 5.99,
    "description": "Ensure your furry friend always finds their way home with this Where My Dogs At Collar Tag. This tag is made of durable metal and features a fun design that will make your dog the talk of the town. It also includes a metal ring that makes it easy to attach to your dog's collar.",
    "image": "https://via.placeholder.com/400x400?text=Placeholder"
}

### Update product
PUT /
Host: localhost:3002
Content-Type: application/json

{
    "id": 11,
    "name": "Where My Dogs At Digital Collar Tag",
    "price": 5.99,
    "description": "Ensure your furry friend always finds their way home with this Where My Dogs At Digital Collar Tag. This digital tag uses low energy bluetooth to connect to your phone and features a fun design that will make your dog the talk of the town. It also includes a metal ring that makes it easy to attach to your dog's collar.",
    "image": "https://via.placeholder.com/400x400?text=Placeholder"
}

### Get product by id
GET /11
Host: localhost:3002

### Delete product by id
DELETE /11 
Host: localhost:3002