### Send order to order service
POST /
Host: localhost:3000
Content-Type: application/json

{
    "customerId": "1234567890",
    "items": [
        {
            "product": 1,
            "quantity": 1,
            "price": 10
        },
        {
            "product": 2,
            "quantity": 2,
            "price": 20
        }
    ]
}

### Virtual worker order processing
GET /
Host: localhost:4001

### Fetch orders from rabbitmq and put into redis
GET /fetch
Host: localhost:3001

### Pick up an order from makeline service for processing
GET /order/57838
Host: localhost:3001

### Put the order back as it is not processed
PUT /order/57838/incomplete
Host: localhost:3001

### Put the order in mongodb as it has been processed
PUT /order/57838/complete
Host: localhost:3001