apiVersion: v1
kind: Service
metadata:
  name: virtual-customer
  namespace: myappproject
spec:
  selector:
    app: virtual-customer   # Seleciona o pod pelo label 'app: virtual-customer'
  ports:
    - protocol: TCP
      port: 80               # Porta interna do serviço
      targetPort: 8080       # Porta do contêiner que o serviço irá expor
  type: ClusterIP            # Tipo do serviço para comunicação interna no cluster