apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-admin
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: store-admin
  template:
    metadata:
      labels:
        app: store-admin
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: store-admin
        image: {{ .Values.storeAdmin.image.repository }}:{{ .Values.storeAdmin.image.tag }}
        ports:
        - containerPort: 8081
          name: store-admin         # container images hosted on ghcr.io and will be removed in future releases
        resources:
          requests:
            cpu: 1m
            memory: 200Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          httpGet:
            path: /health
            port: 8081
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          failureThreshold: 5
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: store-admin
spec:
  type: {{ .Values.storeAdmin.serviceType }}
  ports:
  - port: 80
    targetPort: 8081
  selector:
    app: store-admin