apiVersion: azmonitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product-service-monitor
spec:
  selector:
    matchLabels:
      app: product-service
  endpoints:
    - port: http
      path: /metrics
      interval: 60s
