### Get product service health
GET /health
Host: localhost:3002

### Get products
GET /
Host: localhost:3002

### Add product
POST /
Host: localhost:3002
Content-Type: application/json

{
    "id": 0,
    "name": "Where My Dogs At Collar Tag",
    "price": 5.99,
    "description": "Ensure your furry friend always finds their way home with this Where My Dogs At Collar Tag. This tag is made of durable metal and features a fun design that will make your dog the talk of the town. It also includes a metal ring that makes it easy to attach to your dog's collar.",
    "image": "/placeholder.png"
}

### Update product with too short of a description
PUT /
Host: localhost:3002
Content-Type: application/json

{
    "id": 11,
    "name": "Where My Dogs At Digital Collar Tag",
    "price": 105.99,
    "description": "Tag your dog",
    "image": "/placeholder.png"
}

### Update product with invalid price
PUT /
Host: localhost:3002
Content-Type: application/json

{
    "id": 11,
    "name": "Where My Dogs At Digital Collar Tag",
    "price": 105.99,
    "description": "Ensure your furry friend always finds their way home with this Where My Dogs At Digital Collar Tag. This digital tag uses low energy bluetooth to connect to your phone and features a fun design that will make your dog the talk of the town. It also includes a metal ring that makes it easy to attach to your dog's collar.",
    "image": "/placeholder.png"
}

### Update product
PUT /
Host: localhost:3002
Content-Type: application/json

{
    "id": 11,
    "name": "Where My Dogs At Digital Collar Tag",
    "price": 5.99,
    "description": "Ensure your furry friend always finds their way home with this Where My Dogs At Digital Collar Tag. This digital tag uses low energy bluetooth to connect to your phone and features a fun design that will make your dog the talk of the town. It also includes a metal ring that makes it easy to attach to your dog's collar.",
    "image": "/placeholder.png"
}

### Get product by id
GET /11
Host: localhost:3002

### Delete product by id
DELETE /11 
Host: localhost:3002

### Get ai service health
GET /ai/health
Host: localhost:3002

### Get product description from ai service
POST /ai/generate/description
Host: localhost:3002
Content-Type: application/json

{
    "name": "Seafarer's Tug Rope",
    "tags": ["toy","dog"]
}


### Get product image from ai service
POST /ai/generate/image
Host: localhost:3002
Content-Type: application/json

{
    "name": "Seafarer's Tug Rope",
    "description": "Engage your pup in a game of tug-of-war with the Seafarer's Tug Rope. Made from durable materials, this toy is perfect for interactive playtime and bonding with your furry friend."
}

