### Get ai service health
GET /health
Host: localhost:5001

### Generate product description
POST /generate/description 
Host: localhost:5001
Content-Type: application/json

{
    "name": "Seafarer's Tug Rope",
    "tags": ["toy","dog"]
}

### Generate product image
POST /generate/image 
Host: localhost:5001
Content-Type: application/json

{
    "name": "Seafarer's Tug Rope",
    "description": "Engage your pup in a game of tug-of-war with the Seafarer's Tug Rope. Made from durable materials, this toy is perfect for interactive playtime and bonding with your furry friend."
}
