name: ACR Build

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish-container-image:
  
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        apps: [ # ignore error here
          ai-service,
          makeline-service,
          order-service,
          product-service,
          store-admin,
          store-front,
          virtual-customer,
          virtual-worker
        ]

    steps:
      - name: Set environment variables
        id: set-variables
        run: |
          echo "IMAGE=${{ matrix.apps }}" >> "$GITHUB_OUTPUT"

      - name: Env variable output
        id: test-variables
        run: |
          echo ${{ steps.set-variables.outputs.IMAGE }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ VARS.ACR_REGISTRY }}
          username: ${{ secrets.ACR_CLIENT_ID }}
          password: ${{ secrets.ACR_CLIENT_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: src/${{ matrix.apps }}
          file: src/${{ matrix.apps }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ VARS.ACR_REGISTRY }}/${{ steps.set-variables.outputs.IMAGE }}:latest
            ${{ VARS.ACR_REGISTRY }}/${{ steps.set-variables.outputs.IMAGE }}:${{ github.sha }}
