name: Scan Bicep code
on:
  push:
    branches:
      - main
    paths:
      - "infra/bicep/**"
  pull_request:
    branches:
      - main
    paths:
      - "infra/bicep/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Run PSRule analysis
        uses: microsoft/ps-rule@46451b8f5258c41beb5ae69ed7190ccbba84112c # v2.9.0
        with:
          modules: PSRule.Rules.Azure
          baseline: Azure.Pillar.Security
          inputPath: infra/bicep/*.test.bicep
          outputFormat: Sarif
          outputPath: reports/ps-rule-results.sarif
          summary: true
        continue-on-error: true

        env:
          PSRULE_CONFIGURATION_AZURE_BICEP_FILE_EXPANSION: "true"
          PSRULE_CONFIGURATION_AZURE_BICEP_FILE_EXPANSION_TIMEOUT: "30"

      - name: Upload alerts to Security tab
        uses: github/codeql-action/upload-sarif@ff0a06e83cb2de871e5a09832bc6a81e7276941f # v3
        if: github.repository_owner == 'Azure-Samples'
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
