name: test-playwright

on:
  workflow_call:
    inputs:
      storeAdminUrl:
        required: true
        type: string
      storeFrontUrl:
        required: true
        type: string

jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Azure CLI login
        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install dependencies
        run: npm ci
        working-directory: tests

      - name: Wait for services to be ready
        uses: ./.github/actions/wait-for-services
        with:
          store-front-url: ${{ inputs.storeFrontUrl }}

      - name: Run Playwright tests
        run: npx playwright test --config=playwright.service.config.ts --workers=20
        working-directory: tests
        env:
          PLAYWRIGHT_SERVICE_URL: ${{ secrets.PLAYWRIGHT_SERVICE_URL }}
          SERVICE_STORE_ADMIN_ENDPOINT_URL: ${{ inputs.storeAdminUrl }}
          SERVICE_STORE_FRONT_ENDPOINT_URL: ${{ inputs.storeFrontUrl }}
          COMPANY_NAME: "Contoso"
          CI: true
